
cc_binary(
  name = "cpp-playground",
  deps = [
    "@com_google_absl//absl/strings",
    "@com_google_absl//absl/log",
    "//bazel/cpp:com_github_fmtlib_fmt",
    "//bazel/cpp:com_github_gabime_spdlog",
  ],
  srcs = glob(["src/**"]),
)

